### ISSUE TITLE
Option to configure multiple source directories

### ISSUE THREAD

**Issue by kl3ryk** [goreutils/gore-gulp#1]
In `package.json` eg:
```json
    "directories": {
        "lib": "Src/Acme/**Bundle/Resources/public/js/"
    },
```

This feature will be appreciated by symfony developers. Applications written in symfony consist from Bundles. Each bundle can have it's own resources - images, javascripts, stylesheets etc. Eg.:
```
Src/Acme/FooBundle/Resources/public/js/
Src/Acme/BarBundle/Resources/public/js/
Src/Acme/BazBundle/Resources/public/js/
```
So we have javascript files splitted logically into different directories. There should be possibility to import files between bundles transparently. Eg.:
Should be
```js
import Foo from "Bar"
```
Insetead of
```js
import Foo from "Src/Acme/BarBundle/Resources/public/js/Bar"
```

**Comment by mcharytoniuk** [comment]
My proposal is to use prefixed library names. If you are using single entry point this configuration file is sufficient:

```JSON
{
    "directories": {
        "dest": "dest",
        "lib": "src"
    },
    "name": "my-package"
}
```

If you want to configure several entry points you can use both glob pattern and prefixed names:

```JSON
{
    "directories": {
        "lib1.dest": "dest",
        "lib1.lib": "src/lib1",
        "lib2.dest": "dest",
        "lib2.lib": "src/lib2"
    },
    "name": "my-package"
}
```

**Comment by mcharytoniuk** [comment]
Doable via:

```JSON
{
  "directories": {
    "lib": [ 
      "firstlib",
      "secondlib"
    ]
  }
}
```
