### ISSUE TITLE
Come join me...

### ISSUE THREAD

**Issue by lookfirst** [goreutils/gore-gulp#15]
> "Currently for my job I maintain almost 10 production websites and I find copy-pasting configuration files or even generating project stubs with generators like yeoman really painful (with all respect to yeoman, scaffolding just does not suit my needs)."

We feel the same pain. https://github.com/lookfirst/gulp-helpers

**Comment by mcharytoniuk** [comment]
`gore-gulp` aims to provide just the one-line configuration to make `gulpfile.js` as simple as possible. I think it would be possible for `gore-gulp` to use some of `gulp-helpers` predefined tasks as a part of an internal implementation in the future.

Thanks you for reaching out! :)
