### ISSUE TITLE
revert no-extra-parens

### ISSUE THREAD

**Issue by mcharytoniuk** [goreutils/gore-gulp#18]
Revert `.eslintrc` `no-extra-parens` options to `2` when https://github.com/eslint/eslint/issues/2367 is resolved.

**Comment by zangrafx** [comment]
[IMHO it was more readable with extra parens](/goreutils/gore-gulp/commit/df14f4f7e1f1d7ed4e2fddb45a3302a2a6e839ec#commitcomment-10959967)
