### ISSUE TITLE
Installing gore-gulp and gulp-eslint at the same time causes module loading errors.

### ISSUE THREAD

**Issue by kl3ryk** [goreutils/gore-gulp#21]
[![Build Status](http://img.shields.io/travis/goreutils-tests/gore-gulp-issue-21.svg?style=flat)](https://travis-ci.org/goreutils-tests/gore-gulp-issue-21)

Example package.json:
```json
{
    "devDependencies": {
        "gore-gulp": "0.x",
        "gulp-eslint": "0.x"
    }
}
```

**Comment by mcharytoniuk** [comment]
Test build: https://travis-ci.org/goreutils-tests/gore-gulp-issue-21/builds/60117882
Test repository: https://github.com/goreutils-tests/gore-gulp-issue-21

**Comment by mcharytoniuk** [comment]
This issue was resolved by adding the `postinstall` script to package.json to ensure the local copy of gulp-eslint:
https://github.com/goreutils/gore-gulp/blob/364d160a1b208dce2530baecf90d57b85156d593/package.json#L44
