### ISSUE TITLE
revert eslint space-in-brackets

### ISSUE THREAD

**Issue by mcharytoniuk** [goreutils/gore-gulp#25]
Revert `space-in-brackets` to `[2, "never"]` when this issue is published:  https://github.com/eslint/eslint/issues/2378 in the next eslint version.

**Comment by zangrafx** [comment]
Fix: space-in-brackets import declaration is published with the latest version of [eslint 0.21](https://github.com/eslint/eslint/blob/master/CHANGELOG.md) so I guess now you can revert.
