### ISSUE TITLE
implement eslint shareable configs

### ISSUE THREAD

**Issue by mcharytoniuk** [goreutils/gore-gulp#38]
Use this new eslint feature to distribute gore-gulp eslint config:
https://github.com/eslint/eslint/blob/master/docs/developer-guide/shareable-configs.md

**Comment by mcharytoniuk** [comment]
This issue can be implemented once eslint/eslint#2487 is fixed.

**Comment by zangrafx** [comment]
eslint/eslint#2487 is fixed, can this feature be implemented now?

**Comment by mcharytoniuk** [comment]
Done, thanks. :) :+1:

**Comment by zangrafx** [comment]
Nice, now I can use it in gore-gulp-sublime-text :)
